chrome:
  path: "C:/Program Files/Google/Chrome/Application/chrome.exe"  # Adjust for your system
  args:
    - "--no-sandbox"
    - "--disable-setuid-sandbox"
    - "--disable-gpu"
    - "--disable-dev-shm-usage"
    - "--remote-debugging-port=9222"